// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXIYZdr8uwcgFiFRUc4o6DcPT03cBH2c',
    appId: '1:835690708847:web:64af0a50b0d9c2fd33729a',
    messagingSenderId: '835690708847',
    projectId: 'todo-ab04b',
    authDomain: 'todo-ab04b.firebaseapp.com',
    storageBucket: 'todo-ab04b.appspot.com',
    measurementId: 'G-6XQZ3LS15P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKi0CFllvY5sXuunnZY9L3_7ELfFDj_m4',
    appId: '1:835690708847:android:d358ed85021e980933729a',
    messagingSenderId: '835690708847',
    projectId: 'todo-ab04b',
    storageBucket: 'todo-ab04b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LpuAZerF_DjcnDgTeLOUbrknRQ6OVcc',
    appId: '1:835690708847:ios:7caad7e9b55e111e33729a',
    messagingSenderId: '835690708847',
    projectId: 'todo-ab04b',
    storageBucket: 'todo-ab04b.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6LpuAZerF_DjcnDgTeLOUbrknRQ6OVcc',
    appId: '1:835690708847:ios:7caad7e9b55e111e33729a',
    messagingSenderId: '835690708847',
    projectId: 'todo-ab04b',
    storageBucket: 'todo-ab04b.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeXIYZdr8uwcgFiFRUc4o6DcPT03cBH2c',
    appId: '1:835690708847:web:063740daf6ba16bb33729a',
    messagingSenderId: '835690708847',
    projectId: 'todo-ab04b',
    authDomain: 'todo-ab04b.firebaseapp.com',
    storageBucket: 'todo-ab04b.appspot.com',
    measurementId: 'G-5K19RJ6HZ2',
  );
}
